// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire_test

import (
	"github.com/ishkawa/wire_example/domain"
	"github.com/ishkawa/wire_example/domain/mock_domain"
)

// Injectors from wire.go:

func InitializeFooService(provider *mock_domain.Provider) domain.FooService {
	mockFooRepository := mock_domain.ProvideFooRepository(provider)
	fooService := domain.NewFooService(mockFooRepository)
	return fooService
}
