// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire_test

import (
	"github.com/golang/mock/gomock"
	"github.com/ishkawa/wire_example/domain"
	"github.com/ishkawa/wire_example/domain/mock_domain"
)

// Injectors from wire.go:

func InitializeFooService(ctrl *gomock.Controller) domain.FooService {
	mockFooRepository := mock_domain.NewMockFooRepository(ctrl)
	fooService := domain.NewFooService(mockFooRepository)
	return fooService
}
