// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package mock_domain

import (
	"github.com/golang/mock/gomock"
	"github.com/google/wire"
	"github.com/ishkawa/wire_example/domain"
)

// Injectors from wire.go:

func InitializeFooService(provider *MockRepositorySet) domain.FooService {
	mockFooRepository := ProvideFooRepository(provider)
	fooService := domain.NewFooService(mockFooRepository)
	return fooService
}

// wire.go:

type MockRepositorySet struct {
	MockFooRepository *MockFooRepository
}

func NewRepositorySet(ctrl *gomock.Controller) *MockRepositorySet {
	return &MockRepositorySet{
		MockFooRepository: NewMockFooRepository(ctrl),
	}
}

func ProvideFooRepository(repositorySet *MockRepositorySet) *MockFooRepository {
	return repositorySet.MockFooRepository
}

var providerSet = wire.NewSet(domain.WireSet, ProvideFooRepository, wire.Bind(new(domain.FooRepository), new(MockFooRepository)))
