// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package mock_domain

import (
	"github.com/golang/mock/gomock"
	"github.com/google/wire"
	"github.com/ishkawa/wire_example/domain"
)

// Injectors from wire.go:

func InitializeFooService(provider *Provider) domain.FooService {
	mockFooRepository := ProvideFooRepository(provider)
	fooService := domain.NewFooService(mockFooRepository)
	return fooService
}

// wire.go:

type Provider struct {
	MockFooRepository *MockFooRepository
}

func NewProvider(ctrl *gomock.Controller) *Provider {
	return &Provider{
		MockFooRepository: NewMockFooRepository(ctrl),
	}
}

func ProvideFooRepository(provider *Provider) *MockFooRepository {
	return provider.MockFooRepository
}

var WireSet = wire.NewSet(
	ProvideFooRepository, wire.Bind(new(domain.FooRepository), new(MockFooRepository)))
